alias App.Repo
alias App.Customers
alias App.Customers.Customer
alias App.Sales
alias App.Sales.Sale
alias App.Companies
alias App.Companies.Company
alias App.Installments
alias App.Installments.Installment
